#!/bin/bash

declare CONFIG_FILE="/etc/setacl-helper.conf"

if [ ! -f $CONFIG_FILE ]; then
    echo "Configuration file not found: $CONFIG_FILE"
    exit 1
fi
if [ $# -lt 1 ]; then
    echo "Usage: $0 <path>"
    exit 1
fi

while read line; do
    # Remove comments that # and after
    line=$(echo "$line" | sed 's/#.*//')
    # Skip empty lines
    [[ -z "${line//[[:space:]]/}" ]] && continue
    
    device_path=$(echo "$line" | awk '{print $2}')
    device_path=$(realpath "$device_path")
    [ "$device_path" != "$1" ] && continue

    allowed_user=$(echo "$line" | awk '{print $1}')
    acl=$(stat -c %A "$1" | cut -c 2-4)
    setfacl -m u:$allowed_user:$acl "$1"

done < $CONFIG_FILE
